# Common Labels
labels:
  app: "apply-workflow"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "apply-workflow"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: false

# Container Configs
image:
  repository: "apply-workflow"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/apply-workflow/health"
  readinessProbePath: "/apply-workflow/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
notification-sms-enabled: ""
employee-allowed-search-params: ""
citizen-allowed-search-params: ""

# Additional Container Envs
env: |
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-host
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: NOTIFICATION_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: ASSESSMENT_WORKFLOW_ENABLED
    value: "false"
  - name: EGOV_IDGEN_ACK_FORMAT
    value: {{ index .Values "egov-idgen-ack-format" | quote }}
  - name: EGOV_USER_EVENT_NOTIFICATION_ENABLED
    value: "true"
  {{- if index .Values "employee-allowed-search-params" }}
  - name: EMPLOYEE_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "employee-allowed-search-params" | quote }}
  {{- end }}
  {{- if index .Values "citizen-allowed-search-params" }}
  - name: CITIZEN_ALLOWED_SEARCH_PARAMS
    value: {{ index .Values "citizen-allowed-search-params" | quote }}
  {{- end }}
  - name: EGOV_UI_APP_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
